### ISSUE TITLE
Building from source not possible (Various problems)

### ISSUE THREAD

**Issue by nerone-github** [jilleb/mqb-pm#5]
Hi, i just tried to build from source, however it is not possible to build correctly since the google-services.json file is missing.

Please provide instructions how it is possible to build from source :) 

![image](https://user-images.githubusercontent.com/10217641/35934512-1e4d3954-0c3e-11e8-9952-2ac7cf3c52c3.png)

Second problem:

android:background=" @ drawable/ic_none"  

Missing drawable

**Comment by jilleb** [comment]
The google-services.json was left out, because it contains my API key, and I don't really like the idea of others using my api key ;-) But.... you can easily make your own, check the answers to this:
[stackoverflow topic](https://stackoverflow.com/questions/34367870/where-do-i-get-a-google-services-json)

About the missing drawable: I'll fix that with a new commit today! my bad ;-)

**Comment by jilleb** [comment]
Fixed the missing drawable in the latest commit.
