### ISSUE TITLE
Version number is missing in the app-list

### ISSUE THREAD

**Issue by jilleb** [jilleb/mqb-pm#59]
![image](https://user-images.githubusercontent.com/8352494/62154504-22b5e600-b307-11e9-9dca-77a159e5e66c.png)

**Comment by mobrembski** [comment]
Unfortunately, i cannot reproduce it since new android auto design is not available in my country :/
(I've updated Android Auto to 4.5, latest version but i still have old layout in car).
However, i've found out that Application Manager in android settings show up that Performance Monitor has version number null :)
This patch fixes it, and i belive it will also fix this one
https://github.com/jilleb/mqb-pm/pull/63

**Comment by jilleb** [comment]
Haha thanks! I'll merge it soon :-)

**Comment by jilleb** [comment]
Merged with caa59b856027f18d8f1b9e91741303111d1d5fd1, closing. Thanks!!
